// <auto-generated />
namespace WeChatForTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update10132 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update10132));
        
        string IMigrationMetadata.Id
        {
            get { return "201710130307153_update10132"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
