// <auto-generated />
namespace WeChatForTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class update1012 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update1012));
        
        string IMigrationMetadata.Id
        {
            get { return "201710120150263_update1012"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
