// <auto-generated />
namespace WeChatForTraining.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addMig0922 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addMig0922));
        
        string IMigrationMetadata.Id
        {
            get { return "201709220815017_addMig0922"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
